name: Build App
run-name: Build App
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'

  workflow_dispatch:
    inputs:
      merge-pr:
        type: number
        required: false
        description: Merge a specific PR (by PR number) before building.

jobs:
  collect-build-info:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      version: ${{ steps.get-version.outputs.version }}
      build-notes: ${{ steps.generate-build-notes.outputs.build-notes }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          filter: 'blob:none' # https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/#user-content-blobless-clones
      - name: Get version
        id: get-version
        run: |
          version_tag=$(git describe --tags || echo "v0.0.0-$(git rev-list --count HEAD)-$(git rev-parse --short=8 HEAD)")
          version="${version_tag/#v/}"
          echo "Version: $version"
          echo "version=${version}" >> $GITHUB_OUTPUT
      - name: Generate build notes
        id: generate-build-notes
        uses: zetavg/generate-build-notes-action@v0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build-ios-app:
    needs:
      - collect-build-info
    uses: ./.github/workflows/build-ios-app.yml
    secrets: inherit
    permissions:
      contents: read
      pull-requests: read
    with:
      environment: iOS
      version: ${{ needs.collect-build-info.outputs.version }}
      changelog: ${{ needs.collect-build-info.outputs.build-notes }}

  publish-results:
    needs:
      - collect-build-info
      - build-ios-app
    runs-on: ubuntu-latest
    steps:
      - name: Publish results
        run: |
          echo "Version: ${{ needs.collect-build-info.outputs.version }}"
          echo "iOS build number: ${{ needs.build-ios-app.outputs.build-number }}"
